name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup JDK 18
        uses: actions/setup-java@v1
        with:
            java-version: '18'
            
      - name: Maven Run Unit Tests
        run: mvn -B test
        
      - name: Maven Package
        run: mvn -B clean package
        
      - name: Deploy to Heroku
        uses: jctaveras/heroku-deploy@v3.1.0
        with:
            email: gyurarybkin@gmail.com
            api_key: bf7a8ee8-da09-49e6-a350-4d95e674e44c
            app_name: rsoi-lab1-yryrybkin
            dockerfile_path: '.'
            process_type: 'web'

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 1
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"